//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMFundamentals
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EF6RecipesContext : DbContext
    {
        public EF6RecipesContext()
            : base("name=EF6RecipesContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Meter> Meters { get; set; }
        public virtual DbSet<Poem> Poems { get; set; }
        public virtual DbSet<Poet> Poets { get; set; }
        public virtual DbSet<vwLibrary> vwLibraries { get; set; }
    }
}
