//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueryEntityDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AssociateContainer : DbContext
    {
        public AssociateContainer()
            : base("name=AssociateContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Associate>().ToTable("Chapter3.Associate"); 
            modelBuilder.Entity<AssociateSalary>().ToTable("Chapter3.AssociateSalary");
            modelBuilder.Entity<AssociateSalary>().HasKey(x => x.SalaryID); 
            base.OnModelCreating(modelBuilder); 
        }
    
        public virtual DbSet<AssociateSalary> AssociateSalaries { get; set; }
        public virtual DbSet<Associate> Associates { get; set; }
    }
}
